# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('ingress', models.TextField(blank=True, max_length=500)),
                ('content', models.TextField(blank=True, max_length=4000)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('tags', models.ManyToManyField(blank=True, to='tags.Tag')),
                ('thumbnail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_article_related_thumb', to='files.Image')),
            ],
        ),
    ]
