# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='object_fit',
            field=models.CharField(default='cover', max_length=50),
        ),
    ]
