# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
        ('tags', '0001_initial'),
        ('articles', '0002_article_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ingress',
            field=markdownx.models.MarkdownxField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tags.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_article_related_thumb', to='files.Image'),
        ),
    ]
