# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 10:03
from __future__ import unicode_literals

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20170818_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingress',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
