# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20170818_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='article',
            name='ingress',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
