# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board', models.CharField(default='', max_length=1000)),
                ('tile_config', models.CharField(default='', max_length=300)),
                ('start_character', models.CharField(default='A', max_length=1)),
                ('end_character', models.CharField(default='B', max_length=1)),
                ('tile_size', models.IntegerField(default=100)),
                ('tile_margin', models.IntegerField(default=0)),
                ('font_size', models.IntegerField(default=16)),
                ('algo', models.IntegerField(default=0)),
            ],
        ),
    ]
