# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='title',
            field=models.CharField(default='Board', max_length=50),
        ),
    ]
