# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('astar', '0003_auto_20171008_0934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TileConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tile_config', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='board',
            name='tile_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='astar.TileConfig'),
        ),
    ]
