# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astar', '0004_auto_20171008_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='tileconfig',
            name='title',
            field=models.CharField(default='Board', max_length=50),
        ),
    ]
