# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astar', '0008_board_prediction_multiplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='prediction_multiplier',
            field=models.FloatField(default=1.0),
        ),
    ]
