# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 15:47
from __future__ import unicode_literals

import abouts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=300)),
                ('start_year', models.IntegerField(default=abouts.models.defaut_year)),
                ('end_year', models.IntegerField(default=abouts.models.defaut_year)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abouts.SkillCategory'),
        ),
        migrations.AddField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='abouts.ExperienceCategory'),
        ),
    ]
