# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0003_auto_20170912_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='weight',
            field=models.IntegerField(default=0),
        ),
    ]
