# Generated by Django 2.1.1 on 2018-09-10 18:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abouts', '0004_skill_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='experience',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abouts.ExperienceCategory'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='end_year',
        ),
        migrations.RemoveField(
            model_name='experience',
            name='start_year',
        ),
        migrations.AddField(
            model_name='experience',
            name='end_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='experience',
            name='start_year',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='abouts.SkillCategory'),
        ),
    ]
