# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 09:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('slug', models.CharField(default='', max_length=100, verbose_name='Slug')),
                ('description', models.TextField(blank=True, max_length=100, verbose_name='Description')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('file', models.FileField(upload_to='images')),
                ('number', models.IntegerField(default=0)),
                ('tags', models.ManyToManyField(to='tags.Tag', verbose_name='Tags')),
            ],
            options={
                'permissions': (('view_image_control_panel', 'Can view image control panel'),),
            },
        ),
    ]
